package com.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    public void setNickName(String nickName) {
        set("nickName", nickName);
    }

    public String getNickName() {
        return getStr("nickName");
    }

    public void setUserName(String userName) {
        set("userName", userName);
    }

    public String getUserName() {
        return getStr("userName");
    }

    public void setPassword(String password) {
        set("password", password);
    }

    public String getPassword() {
        return getStr("password");
    }

    public void setSalt(String salt) {
        set("salt", salt);
    }

    public String getSalt() {
        return getStr("salt");
    }

    public void setStatus(Integer status) {
        set("status", status);
    }

    public Integer getStatus() {
        return getInt("status");
    }

    public void setCreateAt(java.util.Date createAt) {
        set("createAt", createAt);
    }

    public java.util.Date getCreateAt() {
        return get("createAt");
    }

    public void setIp(String ip) {
        set("ip", ip);
    }

    public String getIp() {
        return getStr("ip");
    }

    public void setAvatar(String avatar) {
        set("avatar", avatar);
    }

    public String getAvatar() {
        return getStr("avatar");
    }

    public void setLikeCount(Integer likeCount) {
        set("likeCount", likeCount);
    }

    public Integer getLikeCount() {
        return getInt("likeCount");
    }

}
