package com.ware.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCargoInfo<M extends BaseCargoInfo<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    public void setSuppliesOrderNo(String spec) {
        set("supplies_order_no", spec);
    }

    public void setName(String name) {
        set("supplies_name", name);
    }

    public void setType(String type) {
        set("supplies_type", type);
    }

    public void setUnit(Integer type) {
        set("supplies_unit", type);
    }

    public void setSpec(String type) {
        set("supplies_spec", type);
    }

    public void setCreateTime(Date spec) {
        set("supplies_create_time", spec);
    }

    public void setUpdateTime(Date spec) {
        set("supplies_update_time", spec);
    }

    public void setSuppliesStatus(Integer spec) {
        set("supplies_status", spec);
    }

    public void setSuppliesRemark(String spec) {
        set("supplies_remark", spec);
    }
    public void setSuppliesDelStatus(Integer status) {
        set("del_status", status);
    }


    @Override
    public String toString() {
        return "BaseCargoInfo{}";
    }
}
