package com.ware.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSuppliesUnit<M extends BaseSuppliesUnit<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUnitName(java.lang.String unitName) {
		set("unit_name", unitName);
		return (M)this;
	}
	
	public java.lang.String getUnitName() {
		return getStr("unit_name");
	}

}
