package com.ware.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSupplies<M extends BaseSupplies<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSuppliesOrderNo(java.lang.String suppliesOrderNo) {
		set("supplies_order_no", suppliesOrderNo);
		return (M)this;
	}
	
	public java.lang.String getSuppliesOrderNo() {
		return getStr("supplies_order_no");
	}

	public M setSuppliesName(java.lang.String suppliesName) {
		set("supplies_name", suppliesName);
		return (M)this;
	}
	
	public java.lang.String getSuppliesName() {
		return getStr("supplies_name");
	}

	public M setSuppliesType(java.lang.String suppliesType) {
		set("supplies_type", suppliesType);
		return (M)this;
	}
	
	public java.lang.String getSuppliesType() {
		return getStr("supplies_type");
	}

	public M setSuppliesUnit(java.lang.Integer suppliesUnit) {
		set("supplies_unit", suppliesUnit);
		return (M)this;
	}
	
	public java.lang.Integer getSuppliesUnit() {
		return getInt("supplies_unit");
	}

	public M setSuppliesSpec(java.lang.String suppliesSpec) {
		set("supplies_spec", suppliesSpec);
		return (M)this;
	}
	
	public java.lang.String getSuppliesSpec() {
		return getStr("supplies_spec");
	}

	public M setSuppliesCreateTime(java.util.Date suppliesCreateTime) {
		set("supplies_create_time", suppliesCreateTime);
		return (M)this;
	}
	
	public java.util.Date getSuppliesCreateTime() {
		return get("supplies_create_time");
	}

	public M setSuppliesUpdateTime(java.util.Date suppliesUpdateTime) {
		set("supplies_update_time", suppliesUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getSuppliesUpdateTime() {
		return get("supplies_update_time");
	}

	public M setSuppliesStatus(java.lang.Integer suppliesStatus) {
		set("supplies_status", suppliesStatus);
		return (M)this;
	}
	
	public java.lang.Integer getSuppliesStatus() {
		return getInt("supplies_status");
	}

	public M setSuppliesRemark(java.lang.String suppliesRemark) {
		set("supplies_remark", suppliesRemark);
		return (M)this;
	}
	
	public java.lang.String getSuppliesRemark() {
		return getStr("supplies_remark");
	}

	public M setDelStatus(java.lang.Integer delStatus) {
		set("del_status", delStatus);
		return (M)this;
	}
	
	public java.lang.Integer getDelStatus() {
		return getInt("del_status");
	}

}
