package com.ware.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSuppliesInput<M extends BaseSuppliesInput<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setInputCount(java.lang.String inputCount) {
		set("input_count", inputCount);
		return (M)this;
	}
	
	public java.lang.String getInputCount() {
		return getStr("input_count");
	}

	public M setInputTime(java.util.Date inputTime) {
		set("input_time", inputTime);
		return (M)this;
	}
	
	public java.util.Date getInputTime() {
		return get("input_time");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setSuppliesId(java.lang.Integer suppliesId) {
		set("supplies_id", suppliesId);
		return (M)this;
	}
	
	public java.lang.Integer getSuppliesId() {
		return getInt("supplies_id");
	}

}
