package com.ware.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSuppliesManager<M extends BaseSuppliesManager<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setInitialCount(java.lang.Integer initialCount) {
		set("initial_count", initialCount);
		return (M)this;
	}
	
	public java.lang.Integer getInitialCount() {
		return getInt("initial_count");
	}

	public M setRealTimeCount(java.lang.Integer realTimeCount) {
		set("real_time_count", realTimeCount);
		return (M)this;
	}
	
	public java.lang.Integer getRealTimeCount() {
		return getInt("real_time_count");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setWarngingCount(java.lang.Integer warngingCount) {
		set("warnging_count", warngingCount);
		return (M)this;
	}
	
	public java.lang.Integer getWarngingCount() {
		return getInt("warnging_count");
	}

	public M setSuppliesId(java.lang.Integer suppliesId) {
		set("supplies_id", suppliesId);
		return (M)this;
	}
	
	public java.lang.Integer getSuppliesId() {
		return getInt("supplies_id");
	}

	public M setSuppliesTime(java.lang.String suppliesTime) {
		set("supplies_time", suppliesTime);
		return (M)this;
	}
	
	public java.lang.String getSuppliesTime() {
		return getStr("supplies_time");
	}

}
