package com.ware.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSuppliesOutput<M extends BaseSuppliesOutput<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOutputCount(java.lang.Integer outputCount) {
		set("output_count", outputCount);
		return (M)this;
	}
	
	public java.lang.Integer getOutputCount() {
		return getInt("output_count");
	}

	public M setOutputTime(java.util.Date outputTime) {
		set("output_time", outputTime);
		return (M)this;
	}
	
	public java.util.Date getOutputTime() {
		return get("output_time");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setSuppliesId(java.lang.Integer suppliesId) {
		set("supplies_id", suppliesId);
		return (M)this;
	}
	
	public java.lang.Integer getSuppliesId() {
		return getInt("supplies_id");
	}

}
