package com.ware.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("supplies", "id", Supplies.class);
		arp.addMapping("supplies_input", "id", SuppliesInput.class);
		arp.addMapping("supplies_manager", "id", SuppliesManager.class);
		arp.addMapping("supplies_output", "id", SuppliesOutput.class);
		arp.addMapping("supplies_unit", "id", SuppliesUnit.class);
		arp.addMapping("system_user", "id", SystemUser.class);
	}
}

