package com.ware.model;

import com.ware.model.base.BaseSupplies;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Supplies extends BaseSupplies<Supplies> {
	public static final Supplies dao = new Supplies().dao();
}
