package com.ware.model;

import com.ware.model.base.BaseSuppliesInput;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuppliesInput extends BaseSuppliesInput<SuppliesInput> {
	public static final SuppliesInput dao = new SuppliesInput().dao();
}
