package com.ware.model;

import com.ware.model.base.BaseSuppliesOutput;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuppliesOutput extends BaseSuppliesOutput<SuppliesOutput> {
	public static final SuppliesOutput dao = new SuppliesOutput().dao();
}
