package com.ware.model;

import com.ware.model.base.BaseSuppliesUnit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuppliesUnit extends BaseSuppliesUnit<SuppliesUnit> {
	public static final SuppliesUnit dao = new SuppliesUnit().dao();
}
