package com.ware.model;

import com.ware.model.base.BaseSuppliesManager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuppliesManager extends BaseSuppliesManager<SuppliesManager> {
	public static final SuppliesManager dao = new SuppliesManager().dao();
}
