package com.ware.model;

import com.ware.model.base.BaseSystemUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemUser extends BaseSystemUser<SystemUser> {
	public static final SystemUser dao = new SystemUser().dao();
}
